gu_arch.h: fix build with musl (no bits/wordsize.h)
musl libc does not provide <bits/wordsize.h>, causing build to fail:

galerautils/src/gu_arch.h:54:11: fatal error: 'bits/wordsize.h' file not found
   54 | # include <bits/wordsize.h>
      |           ^~~~~~~~~~~~~~~~~

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>