PXC-414: Update ssize_t with size_t wrt. upstream updates
In upstream, ssize_t was replaced with size_t in few places:
026793e615f64a64a423841c5ee7f087856121d0 and
aafd799f680e35801e3c6268e80a37ed654974af

This commit updates our code for that.

Also fixes build error:

```
    gcache/src/gcache_rb_store.cpp: In member function 'gcache::BufferHeader* gcache::RingBuffer::get_new_buffer(gcache::MemOps::size_type)':
    gcache/src/gcache_rb_store.cpp:231:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
            if (max_used > max_used_)
                      ^
```

Also note, following removed:

        galera/src/wsrep_api.h - REMOVED upstream
        galerautils/src/galerautils.hpp  - REMOVED upstream
        gcache/src/pasture/   - REMOVED upstream
        man/garbd.1     - Renamed to garbd.8
        scripts/packages/galera.spec - Obsolete.

The ones removed upstream have been moved elsewhere in some cases. Refer
to aafd799f680e35801e3c6268e80a37ed654974af for details.